project_id = "srwuprrcbfuzvkehvgyt"

[functions.ai-training-coach]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.garmin-connect]
verify_jwt = true

[functions.garmin-auth]
verify_jwt = false

[functions.strava-auth]
verify_jwt = false

[functions.strava-sync]
verify_jwt = true