project_id = "srwuprrcbfuzvkehvgyt"

[functions.ai-training-coach]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.garmin-connect]
verify_jwt = true

[functions.strava-oauth]
verify_jwt = true

[functions.strava-sync]
verify_jwt = true