project_id = "srwuprrcbfuzvkehvgyt"

[functions.ai-training-coach]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.garmin-oauth]
verify_jwt = false

[functions.garmin-backfill]
verify_jwt = true

[functions.garmin-webhook]
verify_jwt = false

[functions.strava-auth]
verify_jwt = false

[functions.strava-sync]
verify_jwt = true