// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srwuprrcbfuzvkehvgyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyd3VwcnJjYmZ1enZrZWh2Z3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMjQ0NTYsImV4cCI6MjA3MzkwMDQ1Nn0.mysBeAiZM8AjyWKHQs_0ZJUgvMijk-yRyeFfQE7KT2M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});